name: flutter_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # flutter
  provider: ^6.0.5
  intl: ^0.17.0

  # facilities
  url_launcher: ^6.1.7

  # design
  cupertino_icons: ^1.0.5

  # 3rd party libraries
  google_sign_in: ^5.4.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true